spring:
  application:
    name: auth
  mvc:
    dispatchOptionsRequest: true
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: ${DATABASE_3}
    username: ${USER_DATABASE_3}
    password: ${PW_DATABASE_3}
    driver-class-name: oracle.jdbc.OracleDriver 
    platform: oracle
  jpa:
    database: ORACLE
    show-sql: false
    
server:
  port: 8007

logging:
  level:
    org.springframework.security: DEBUG
  
keystore:
  password: automagic
  
eureka:
  instance:
    hostname: ${DOCKER_HOST_IP:localhost}
    instance-id: ${spring.application.name}:${server.port}
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
