spring:
  application:
    name: aw-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: ${DOCKER_HOST_IP:localhost}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
  datacenter: Tampa
  environment: Automagic
