spring:
  application:
    name: aw-eureka
  cloud:
    inetutils:
        preferredNetworks:
          - automagic
          - 52.15.89.219

server:
  port: 8761
#  context-path: /auth

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: Tampa
  environment: Automagic
  
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      clientId: admin
#      clientSecret: octocat
#      accessTokenUri: http://localhost:8761/auth/oauth/token
#      userAuthorizationUri: http://localhost:8761/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8761/auth/user/me
