spring:
  application:
    name: aw-eureka

server:
  port: 8761
#  context-path: /auth

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: Tampa
  environment: Automagic
