server:
  port: 0
spring:
  application:
    name: fullboard
  datasource:
    url: jdbc:oracle:thin:@automagic.cf65nkvvhk0p.us-east-2.rds.amazonaws.com:1521:ORCL
    username: automagic
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle
  jpa:
    database: ORACLE
    show-sql: true  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
