spring:
  application:
    name: aw-zuul

server:
  port: 8765
  
eureka:
  instance:
    hostname: zuul
    instance-id: ${spring.application.name}:${server.port}

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
