spring:
  application:
    name: aw-zuul

server:
  port: 8765
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
  instance:
    hostname: zuul
    instance-id: ${spring.application.name}:${server.port}
    
zuul:
  routes:
    users:
      path: /users/**
      sensitiveHeaders:
      serviceId: users    

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
