#aw-boards
  
spring:
  application:
    name: aw_Boards
    
  rabbitmq:
    host: ${DOCKER_HOST_IP:localhost}
    password: guest
    username: guest
    port: 5672

  cloud:
    stream:
      bindings:
        BoardUserRole:
          destination: bur-rabbit
        Swimlane:
          destination: swimlane-rabbit
   
  mvc:
    dispatchOptionsRequest: true
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: jdbc:oracle:thin:@meanbean.cz7bznkyn7di.us-east-2.rds.amazonaws.com:1521:ORCL
    username: meanbean_user
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle
  jpa:
    database: ORACLE
    show-sql: true
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
  instance:
    hostname: ${DOCKER_HOST_IP:localhost}:${server.port}
    instance-id: ${spring.application.name}:${random.int}

security:
  oauth2:
    resource:
      accessTokenUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/check_token
      userAuthorizationUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/authorize
      userInfoUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/user
      jwt:
        keyUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/token_key

server:
  port: 8002
#  port: 0
  
  
#logging:
#  level:
#    org.springframework.web: ERROR
#    com.revature.aw: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: ./logs/aw_board.log
