server:
  port: 8001
spring:
  application:
    name: aw_BoardValidation
    
  rabbitmq:
    host: ${DOCKER_HOST_IP:localhost}
    password: guest
    username: guest
    port: 5672

  cloud:
    stream:
      bindings:
        input:
          destination: bur-rabbit
    
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: ${DATABASE_1}
    username: ${DATABASE_USER_1}
    password: ${PW_DATABASE_1}
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle 
  jpa:
    database: ORACLE
    show-sql: false           
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
  instance:
    hostname: ${DOCKER_HOST_IP:localhost}:${server.port}
    instance-id: ${spring.application.name}:${random.int}
security:
  oauth2:
    resource:
      accessTokenUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/check_token
      userAuthorizationUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/authorize
      userInfoUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/user
      jwt:
        keyUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/token_key  
