server:
  port: 0
spring:
  application:
    name: aw_BoardValidation
#  cloud:
#    config:
#      uri: http://localhost:9000 
  datasource:
    url: jdbc:oracle:thin:@meanbean.cz7bznkyn7di.us-east-2.rds.amazonaws.com:1521:ORCL
    username: meanbean_user
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle 
  jpa:
    database: ORACLE
    show-sql: true           
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname:
    instance-id:
