server:
  port: 0
spring:
  application:
    name: aw_history
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: jdbc:oracle:thin:@automagic.cf65nkvvhk0p.us-east-2.rds.amazonaws.com:1521/ORCL
    username: automagic
    password: password
    driver-class-name: oracle.jdbc.OracleDriver 

  jpa:
    hibernate: 
      ddl-auto: update
    database: ORACLE
    show-sql: true  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}      
security:
  oauth2:
    resource:
      accessTokenUri: http://localhost:8090/auth/oauth/check_token
      userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
      userInfoUri: http://localhost:8090/auth/user
      jwt:
        keyUri: http://localhost:8090/auth/oauth/token_key  
