server:
  port: 8004
spring:
  application:
    name: aw_history
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: jdbc:oracle:thin:@automagic.cf65nkvvhk0p.us-east-2.rds.amazonaws.com:1521/ORCL
    username: automagic
    password: password
    driver-class-name: oracle.jdbc.OracleDriver 

  jpa:
    hibernate: 
      ddl-auto: update
    database: ORACLE
    show-sql: true  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
  instance:
    hostname: ${DOCKER_HOST_IP:localhost}:${server.port}
    instance-id: ${spring.application.name}:${random.int}      
security:
  oauth2:
    resource:
      accessTokenUri: http://${DOCKER_HOST_IP:localhost}:8090/auth/oauth/check_token
      userAuthorizationUri: http://${DOCKER_HOST_IP:localhost}:8090/auth/oauth/authorize
      userInfoUri: http://${DOCKER_HOST_IP:localhost}:8090/auth/user
      jwt:
        keyUri: http://${DOCKER_HOST_IP:localhost}:8090/auth/oauth/token_key  
        
#logging:
#  level:
#    org.springframework.web: ERROR
#    com.revature.aw: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: ./logs/aw_history.log
