server:
  port: 8004
spring:
  application:
    name: aw_history
  mvc:
    dispatchOptionsRequest: false
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: ${DATABASE_2}
    username: ${USER_DATABASE_2}
    password: ${PW_DATABASE_2}
    driver-class-name: oracle.jdbc.OracleDriver 

  jpa:
    hibernate: 
      ddl-auto: update
    database: ORACLE
    show-sql: false  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
  instance:
    hostname: ${DOCKER_HOST_IP:localhost}
    instance-id: ${spring.application.name}:${random.int}      
security:
  oauth2:
    resource:
      accessTokenUri: http://${DOCKER_HOST_IP:localhost}:8765/auth/oauth/check_token
      userAuthorizationUri: http://${DOCKER_HOST_IP:localhost}:8765/auth/oauth/authorize
      jwt:
        keyUri: http://${DOCKER_HOST_IP:localhost}:8765/auth/oauth/token_key  
