server:
  port: 8003
spring:
  application:
    name: aw_Story
    
  rabbitmq:
    host: ${DOCKER_HOST_IP:localhost}
    password: guest
    username: guest
    port: 5672

  cloud:
    stream:
      bindings:
        input:
          destination: story-rabbit
        Task:
          destination: task-rabbit
          
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: ${DATABASE_3:jdbc:oracle:thin:@macguffin.cfs7tvzcxdyw.us-east-2.rds.amazonaws.com:1521:ORCL}
    username: ${USER_DATABASE_3:macguffin_user}
    password: ${PW_DATABASE_3:p4ssw0rd}
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle
  jpa:
    hibernate: 
      ddl-auto: update
    database: ORACLE
    show-sql: false  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true   
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
  instance:
    hostname: ${DOCKER_HOST_IP:localhost}:${server.port}
    instance-id: ${spring.application.name}:${random.int}
security:
  oauth2:
    resource:
      accessTokenUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/check_token
      userAuthorizationUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/authorize
      userInfoUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/user
      jwt:
        keyUri: http://${DOCKER_HOST_IP:localhost}:8765/users/auth/oauth/token_key    
