server:
  port: 8003
spring:
  application:
    name: aw_Story
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: jdbc:oracle:thin:@macguffin.cfs7tvzcxdyw.us-east-2.rds.amazonaws.com:1521:ORCL
    username: macguffin_user
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle
  jpa:
    hibernate: 
      ddl-auto: update
    database: ORACLE
    show-sql: true  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true   
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP}:8003/story/
  instance:
    hostname: ${DOCKER_HOST_IP}:${server.port}
    instance-id: ${spring.application.name}:${random.int}
security:
  oauth2:
    resource:
      accessTokenUri: http://localhost:8090/auth/oauth/check_token
      userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
      userInfoUri: http://localhost:8090/auth/user
      jwt:
        keyUri: http://localhost:8090/auth/oauth/token_key    
        
        
logging:
  level:
    org.springframework.web: ERROR
    com.revature.aw: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ./logs/aw_story.log
