server:
  port: 0
spring:
  application:
    name: aw_Story
  datasource:
    tomcat:
      initial-size: 1
    url: jdbc:oracle:thin:@meanbean.cz7bznkyn7di.us-east-2.rds.amazonaws.com:1521:ORCL
    username: meanbean_user
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle
  jpa:
    database: ORACLE
    show-sql: true  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true   
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
