server:
  port: 8006
spring:
  application:
    name: tasks
    
  rabbitmq:
    host: ${DOCKER_HOST_IP:localhost}
    password: guest
    username: guest
    port: 5672

  cloud:
    stream:
      bindings:
        input:
          destination: task-rabbit
          
  datasource:
    tomcat:
      initial-size: 1
    max-active: 3  
    url: ${DATABASE_1}
    username: ${USER_DATABASE_1}
    password: ${PW_DATABASE_1}
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle
  jpa: 
    database: ORACLE
    show-sql: false 
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP:localhost}:8761/eureka/
  instance: 
    hostname: ${DOCKER_HOST_IP:localhost}
    instance-id: ${spring.application.name}:${random.int}
security:
  oauth2:
    resource:
      accessTokenUri: http://${DOCKER_HOST_IP:localhost}:8765/auth/oauth/check_token
      userAuthorizationUri: http://${DOCKER_HOST_IP:localhost}:8765/auth/oauth/authorize
      jwt:
        keyUri: http://${DOCKER_HOST_IP:localhost}:8765/auth/oauth/token_key  
